version: '3.4'

services:
  banjax:
    build:
      context: ./
      dockerfile: Dockerfile
    # this uses the nginx network namespace so it can set iptables rules
    # in the right place. the go app listens on port 8081
    network_mode: "service:nginx"
    cap_add:
      - NET_ADMIN  # we use iptables for banning
    volumes:
      - ./logs/banjax:/var/log/banjax/
      - .:/opt/banjax/
    restart: on-failure:5

  nginx:
    build:
      context: ./supporting-containers/nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "8001:8001"
    volumes:
      - ./logs/banjax:/var/log/banjax/
      - ./supporting-containers/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./logs/nginx:/var/log/nginx/

  test-origin:
    build:
      context: ./supporting-containers/test-origin
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  # wrk:
  #   image: ghcr.io/william-yeh/wrk
  #   platform: linux/amd64
  #   volumes:
  #     - ./tmp:/data
  #   command: -t12 -c1024 -d10s http://localhost
  #   # Automatically removes the container when it exits
  #   restart: "no"
  #   network_mode: "service:nginx"
